### ISSUE TITLE
HTTP callbacks for play requests to authenticate clients and dynamically set source address

### ISSUE THREAD

**Issue by Fusl** [fionera/rtsp-simple-server#7]
When a client connects to the rtsp endpoint, rtspss currently unconditionally allows any client to listen to a stream.

This feature request is for an HTTP callback whenever an rtsp client connects: rtspss should send a HTTP request to a preconfigured URL with some client and path information like client IP, client port, server IP, server port, playback path, etc., send that to the HTTP endpoint either as GET requests with URL-encoded query strings or POST requests with a JSON body.

On response, handle the HTTP status as follows:

- HTTP 200-299: Client is allowed to play the path, continue as normal and run through the entire rest of the setup procedure without any changes
- HTTP 300-399: Client is allowed to play the path, but from a different configured `source:` than the one defined in the configuration. The HTTP backend should include a `location` HTTP header with the new proxy source, if that's not the case, close the rtsp client connection. If rtspss would fall back to proxying from `source:` instead of playing a currently running stream (either because there is no stream running at the moment or there are no other listeners attached to an existing source), this would override the configured stream proxy `source:`.
- HTTP 400-499: Client is not allowed to play the path, reject playback as if `readIps` was configured and doesn't match the client IP.
- Any other HTTP code or no HTTP response: Close the connection

**Comment by fionera** [comment]
Closed by #8
